### ISSUE TITLE
Rollermines can't be picked up with the super gravity gun

### ISSUE THREAD

**Issue by Luke18033** [StrataSource/Portal-2-Community-Edition#1107]
### Describe the bug

Attempting to pick up a rollermine with the super gravity gun causes it to create frozen nonsolid duplicates of itself, and not actually be picked up. (This is also an issue in the original HL2)

https://user-images.githubusercontent.com/19228201/211989738-d501fa2f-3da0-4d9a-9faf-1bda3fe80885.mp4

### Issue Map

Any

### To Reproduce

1. Run `give weapon_physcannon;use weapon_physcannon;physcannon_mega_enabled 1;ent_create npc_rollermine`
2. Try to pick up the rollermine

### Operating System

Tested on Windows 10

**Comment by MyGamepedia** [comment]
Something like this also happening if use weapon_hopwire against gunship and rollermine  (but I'm not sure that P2CE use weapon_hopwire).

**Comment by Luke18033** [comment]
We probably don't have the hopwire since it's a beta weapon, but I'd imagine the cause of the bug is the same for both. I haven't tried using the super gravity gun on a gunship.

**Comment by pivotman319-owo** [comment]
> Attempting to pick up a rollermine with the super gravity gun causes it to create frozen nonsolid duplicates of itself, and not actually be picked up. (This is also an issue in the original HL2)

Also breaks both original HL2 and Portal turret entities as well as practically anything that doesn't have a health value. The failing block of code resides at [lines 2374-2393 in `game/server/hl2/weapon_physcannon.cpp`](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/hl2/weapon_physcannon.cpp#L2374-L2393).

`CWeaponPhyscannon` attempts to turn the NPC into a serverside ragdoll by first inflicting 1 damage point, creating a prop_ragdoll that doesn't have collision using the soon-to-be killed NPC as a pointer, and then inflicting 10k damage against it (with `DMG_REMOVENORAGDOLL`) so that it can properly die and have the ragdoll become a grabbable entity. Because neither of these entities (including the rollermine) have proper ragdoll meshes nor do they have an actual health value, prop_ragdoll entities will continue to spawn when +attack2 is held down for every tick:

https://pivotman319-owo.github.io/garbage/chaos_2023-01-14_11-07-44.mp4

**Comment by TeamSpen210** [comment]
Looking at Manhacks, they only have `EFL_NO_MEGAPHYSCANNON_RAGDOLL` set, which would be what we want to have set on all vphysics NPCs so they don't spawn duplicates. There's also `npc_security_camera`, `npc_personality_core`, `noc_wheatley_boss`, `npc_rocket_turret` that should have these set. For rocket turrets and Wheatley probably there should be no interaction at all, while cameras probably should trigger their regular ragdoll behaviour first?

**Comment by pivotman319-owo** [comment]
Fixed in latest dev builds.

https://github.com/StrataSource/Portal-2-Community-Edition/assets/15126754/1ee58b5d-164e-40d0-a9e4-940d6f2f4a49
