### ISSUE TITLE
Bug: Can't switch to paint gun when on dedicated server

### ISSUE THREAD

**Issue by ENDERZOMBI102** [StrataSource/Portal-2-Community-Edition#1191]
### Describe the bug

Trying to switch to the paint gun via the `use weapon_paintgun` when connected to a dedicated server will fail to switch weapon.

### Issue Map

some DM map

### To Reproduce

1. Connect to dedicated server
2. Open console
3. Input `use weapon_paintgun`
4. Go back to game
5. Weapon doesn't switch

may be connected to #1138

**Comment by Luke18033** [comment]
I've never had a problem with this

**Comment by Luke18033** [comment]
Still can't reproduce this
![image](https://user-images.githubusercontent.com/19228201/234175115-b977a34c-0e42-41a4-af24-440493c5ca3a.png)

Note, if you were playing on my deathmatch server and couldn't `use weapon_paintgun`, it's because I just don't give you one on spawn, if you get one manually with `give_paintgun` it should work
