### ISSUE TITLE
Enhancement: Remove weapon_manhack and weapon_thumper

### ISSUE THREAD

**Issue by tmob03** [StrataSource/Portal-2-Community-Edition#1304]
### Which component should be improved?

Entity

### Describe your suggestion

These are broken hl2 beta entities.

And ACTUAL beta entities, these two aren't in HL2, or Portal 1.

**Comment by MyGamepedia** [comment]
OMG! How ? They're disabled in code, like other hl2 beta weapons, isn't so ?

**Comment by JJL772** [comment]
We forgot to remove some

**Comment by pivotman319-owo** [comment]
On a related note, it seems like it's entirely possible to use the stunstick on P2CE; I'd assume this is probably due to missing suit behavior that only exists outside of portal2? I know for a matter of fact that stunsticks are treated as suit batteries, so maybe this that has something to do with it as well.

**Comment by tmob03** [comment]
Done in staging

**Comment by MyGamepedia** [comment]
Is it relevant to this ?

![20230616180320_1](https://github.com/StrataSource/Portal-2-Community-Edition/assets/103366204/1b0768d5-6b3e-42f2-95a8-cccca9f0cc62)

**Comment by AWildErin** [comment]
That entity doesn't exist anymore, it was part of the thumper weapon.
