### ISSUE TITLE
Feature: Hammer Paint Tool for Gels

### ISSUE THREAD

**Issue by Konclan** [StrataSource/Portal-2-Community-Edition#1513]
### Which component should be improved?

Other

### Describe your suggestion

A new tool for hammer called the paint tool that allows you to place Gel on valid surfaces in the editor

Mockup image:
![P2CE Paint Tool](https://github.com/StrataSource/Portal-2-Community-Edition/assets/16567080/58a0e848-35d6-4a30-9d84-c2ec4973b854)

**Comment by JJL772** [comment]
Closing because this is far too much work, unfortunately. Really appreciate the idea and mockups, Ozxy and I think it'd be really cool to have! But yeah, this requires huge changes to hammer, map compilers and the engine. We don't have the bandwidth for this now or in the foreseeable future, and plenty of other features take priority.

**Comment by Konclan** [comment]
This could become a feature of the rewrite instead of a new feature for the current hammer
