### ISSUE TITLE
Gravity Redirection Trigger

### ISSUE THREAD

**Issue by Konclan** [StrataSource/Portal-2-Community-Edition#293]
A trigger that changes the direction of gravity, has flags and filters like other triggers. Rotates the player like adhesion gel.

**Comment by Konclan** [comment]
This is a semi-duplicate of #63 but I assume that want's a point entity or console command, I'm looking for a trigger that players or objects can go in and out of.

**Comment by RedstoneParadox** [comment]
I think rather than making a new trigger, the existing `trigger_gravity` and `trigger_vphysics_motion` should be modified to be able to redirect gravity, mainly because they both already can change the scale of gravity and `trigger_vphysics_motion` has the ability to do things such as changing air drag so having a separate trigger would lead to more clutter and overlapping triggers.

**Comment by ozxybox** [comment]
Closing as duplicate of #1701, as that issue is more detailed
