### ISSUE TITLE
fix multiplayer physics

### ISSUE THREAD

**Issue by AddMGH** [StrataSource/Portal-2-Community-Edition#62]
In Portal 2, almost all of the Multiplayer physics are some of the most bug infested and exploitable parts of the entire game

----

- Cubes can be picked up through grating or any hole that cubes would normally be blocked by
- Cubes can be smuggled under fizzlers by looking down and crouching while going through them

**Comment by SpyceTewan** [comment]
Elaborate please

**Comment by AddMGH** [comment]
Well, in coop you can look at the ground and hold a cube and pass through a fizzler, along with how gratings work which meant BEEmod had to add a custom 'multiplayer' grating.

**Comment by Konclan** [comment]
I think a fix would be to make coop players unable to collide with held objects but keep everything else the same as singleplayer.

**Comment by SpyceTewan** [comment]
Isn't that just a cvar? You can make cubes behave like that in sp

**Comment by Konclan** [comment]
Turning it on is just a bandaid fix though, I'm not sure why in coop held objects are like they are but valve clearly was fixing some sort of issue. I haven't tested sp physics in coop well enough to know what that issue is though.

**Comment by anexistantperson** [comment]
I believe they put it in so players wouldn't have to let go of an object for the other one to grab it, and iirc tewan said they shouldn't do anything that would disbenefit speedrunners. So what I say is since there's already a cvar for it, allow the map makers to set it, or not do anything about it. And it would also allow more map concepts.

**Comment by Luke18033** [comment]
The cvar requires sv_cheats though, so it would be to be changed for that to work. Or allow the grab mode to be set through an entity.

**Comment by Konclan** [comment]
Two major issues with multiplayer held object physics interaction are:
- Cubes can be picked up through grating or any hole that cubes would normally be blocked by
- Cubes can be smuggled under fizzlers by looking down and crouching while going through them

**Comment by Luke18033** [comment]
We could try getting proper physics object grabbing working in multiplayer, though I have the feeling there were good reasons why Valve didn't. So if that doesn't work, there are a couple things we can do to fix viewmodel grabbing instead:
- Prevent held object's hitboxes from clipping through things. This wouldn't fully physically simulate them, but would just push the hitbox back (into the player) when looking near a surface. This solves being able to stick cubes under fizzlers.
- When trying to pick up an object, trace a line between the player's eyes and the object. If it hits something which the object would have collided with, don't pick it up. This solves being able to pick up cubes through grating.

Since this would break existing speedrun strategies, we'd have a cvar to restore the old behavior.

**Comment by Luke18033** [comment]
This issue is too vague, just going to close it
