### ISSUE TITLE
Bug: Some projected textures in the campaign are active before they should be

### ISSUE THREAD

**Issue by ShygalCoco** [StrataSource/Portal-2-Community-Edition#835]
### Describe the bug

Some projected textures in the campaign are active before they should be because there's now support for multiple active projected textures at the same time in P2:CE. Valve originally took advantage of the limitation of only having one active projected texture at a time, specifically having all the other projected textures automatically turn off right when one of them gets an input to turn on. In this video right here, the projected texture that's flickering far infront of me shouldn't be on yet as it should've been turned off at the start of the map by the projected texture that turns on in the arrival elevator room.

https://user-images.githubusercontent.com/69723642/160503624-863e73c6-80bf-4b6c-a4de-00ac478933a1.mp4

### To Reproduce

Go to the area where the video demonstrates and look through the open door at a distance.

### Operating System

Windows 10

**Comment by Luke18033** [comment]
I'm not sure if we can really fix this, besides doing some dumb hack like detecting base P2 maps and limiting them to having one projected texture active...

**Comment by Luke18033** [comment]
Better idea: since we're inevitably going to add more features like this which break backwards compatibility with the campaign(s), maybe we should just patch the entity lumps of specific maps to fix the problem?
There's also still the option of checking the BSP version, which would ensure backwards compat with non-Valve maps as well, though I seem to remember there being some reason we didn't want to do that, and I'm not sure if that's something we need anyway...

Given that this is P2CE, maybe we should ask the community to see whether or not backwards compatibility with base P2 custom maps is something people actually care about?

**Comment by Luke18033** [comment]
How do you plan to fix this, checking the BSP version?

**Comment by craftablescience** [comment]
Fixed in latest
