### ISSUE TITLE
Co-op ping tool uses SP portal colors

### ISSUE THREAD

**Issue by ashifolfi** [StrataSource/Portal-2-Community-Edition#957]
### Describe the bug

I noticed that the ping tool appears to have it's colors influenced by your SP portal color CVars in Co-op? I don't think this is correct at all!

https://user-images.githubusercontent.com/29577987/180836976-c487fff9-227d-435d-b969-3a7b5058da8b.mp4

### Issue Map

All of multiplayer.

### To Reproduce

1. Start up a multiplayer map
2. enable alternate portal colors
3. set your primary/secondary to anything you want
4. the ping tool will have it's color changed with

**Comment by AWildErin** [comment]
Yeah this is a bug I introduced, I was meaning to create a bug report for it but I haven't. I got a feeling, due to what I discovered, this map doesn't actually load you into coop mode (which is really weird) which may influence the issue. If you can test it in actual mp, like split screen or something that'd be great!

**Comment by ashifolfi** [comment]
did test in split screen on an actual coop map. same result

**Comment by AWildErin** [comment]
Alright then, thanks for giving that a test for me!

**Comment by Luke18033** [comment]
Still an issue
![image](https://user-images.githubusercontent.com/19228201/231059557-bdc522d5-8167-4278-894f-87d80c9bd819.png)

**Comment by AWildErin** [comment]
The plan is to fix the fact it uses SP colours. Valve messed up some code, and so did we. Making the MP colours customisable would be possible but that would have to be up to the map rather than the individual player in the case of multiplayer. And such a system isn't in place just yet, so that would be better suited for a different issue than this one.

**Comment by ozxybox** [comment]
Erin has fixed this, should be on the staging branch tonight
